# Generated by Django 4.1.5 on 2023-01-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='subject',
            field=models.CharField(choices=[('select', 'select'), ('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('BIOLOGY', 'BIOLOGY'), ('PHYSICS', 'PHYSICS'), ('SOCIAL STUDIES', 'SOCIAL STUDIES')], max_length=50),
        ),
    ]
