# Generated by Django 4.1.5 on 2023-01-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arapp', '0002_alter_admin_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(choices=[('select', 'select'), ('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('BIOLOGY', 'BIOLOGY'), ('PHYSICS', 'PHYSICS'), ('SOCIAL STUDIES', 'SOCIAL STUDIES')], default=('ENGLISH', 'ENGLISH'), max_length=50),
        ),
        migrations.AlterField(
            model_name='admin',
            name='subject',
            field=models.CharField(choices=[('select', 'select'), ('ENGLISH', 'ENGLISH'), ('MATHEMATICS', 'MATHEMATICS'), ('BIOLOGY', 'BIOLOGY'), ('PHYSICS', 'PHYSICS'), ('SOCIAL STUDIES', 'SOCIAL STUDIES')], default=('ENGLISH', 'ENGLISH'), max_length=50),
        ),
    ]
